# Generated by Django 4.1.13 on 2025-11-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeprofile",
            old_name="salary",
            new_name="ctc",
        ),
    ]
