# Generated by Django 4.1.13 on 2025-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_salary_employeeprofile_ctc"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
