# Generated by Django 4.1.13 on 2026-06-15 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employeeprofile_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with 10 to 15 digits.', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
