# Generated by Django 4.1.13 on 2025-11-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_employeeprofile_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxinfo",
            name="tax_slab",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
