# Generated by Django 4.1.13 on 2026-07-21 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employeeprofile_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must be numeric and should match the Employee ID on the biometric device.', regex='^[0-9]+$')]),
        ),
    ]
