# Generated by Django 4.1.13 on 2025-12-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_taxinfo_tax_slab"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="emp_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
