# Generated by Django 4.1.13 on 2025-12-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_emp_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="degination",
            new_name="designation",
        ),
    ]
