# Generated by Django 4.1.13 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='commonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.TextField(blank=True, default='office, engineer, testing', help_text='Enter department names separated by commas.')),
            ],
            options={
                'verbose_name': 'Common information',
                'verbose_name_plural': 'Common information',
            },
        ),
    ]