# Generated by Django 4.1.13 on 2026-07-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_commoninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoninfo',
            name='departments',
            field=models.TextField(blank=True, default='', help_text='Enter department names separated by commas.'),
        ),
    ]
