# Generated by Django 4.1.13 on 2025-12-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_degination_user_designation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pf_id",
        ),
    ]
