# Generated by Django 4.1.13 on 2025-12-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_pf_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="hire_date",
            new_name="date_of_joining",
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
