# Generated by Django 4.1.13 on 2025-12-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_rename_hire_date_user_date_of_joining_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="current_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="permanent_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="pin_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("unspecified", "Unspecified"),
                ],
                default="unspecified",
                max_length=20,
            ),
        ),
    ]
