# Generated by Django 4.1.13 on 2025-12-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_employeeprofile_city_employeeprofile_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="current_address",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="permanent_address",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="pin_code",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="state",
        ),
    ]
