# Generated by Django 4.1.13 on 2025-12-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_employeeprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="permanent_address",
            field=models.TextField(blank=True),
        ),
    ]
