# Generated by Django 4.1.13 on 2025-12-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_employeeprofile_permanent_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeprofile",
            old_name="address",
            new_name="current_address",
        ),
    ]
