# Generated by Django 4.1.13 on 2025-12-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_rename_address_employeeprofile_current_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="bio",
        ),
    ]
