# Generated by Django 4.1.13 on 2025-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_employeeprofile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxinfo",
            name="insurance_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
