# Generated by Django 4.1.13 on 2025-12-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_taxinfo_insurance_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxinfo",
            name="insurance_number",
        ),
        migrations.CreateModel(
            name="BenefitsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "health_insurance_provider",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "health_insurance_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("other_benefits", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefitsinfo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
