# Generated by Django 4.1.13 on 2025-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_taxinfo_insurance_number_benefitsinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxinfo",
            name="health_insurance_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="taxinfo",
            name="health_insurance_provider",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="taxinfo",
            name="other_benefits",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="BenefitsInfo",
        ),
    ]
