# Generated by Django 4.1.13 on 2025-12-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_taxinfo_health_insurance_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
