# Generated by Django 4.1.13 on 2026-01-08 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_employeeprofile_emergency_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters, spaces, hyphens or apostrophes (no numbers).",
                        regex="^[A-Za-z\\s'-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters, spaces, hyphens or apostrophes (no numbers).",
                        regex="^[A-Za-z\\s'-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters, spaces, hyphens or apostrophes (no numbers).",
                        regex="^[A-Za-z\\s'-]+$",
                    )
                ],
            ),
        ),
    ]
