# Generated by Django 4.1.13 on 2025-11-22 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePayrollDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "special_allowances",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "conveyance_allowances",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "epf_contribution",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "esi_contribution",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tds", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pay_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
