# Generated by Django 4.1.13 on 2025-11-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeepayrolldetails",
            name="pay_date",
        ),
    ]
