# Generated by Django 4.1.13 on 2025-11-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_remove_employeepayrolldetails_pay_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeepayrolldetails",
            name="pay_day",
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
    ]
