# Generated by Django 4.1.13 on 2025-11-28 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0004_advancesalaryrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="advancesalaryrequest",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_advance_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
