# Generated by Django 4.1.13 on 2025-11-30 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0005_advancesalaryrequest_approver"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratePayroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "special_allowances",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "conveyance_allowances",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "epf_contribution",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "esi_contribution",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tds", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bonous",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_generation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
