# Generated by Django 4.1.13 on 2025-11-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_generatepayroll"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatepayroll",
            name="status",
            field=models.CharField(default="Not Paid", max_length=20),
        ),
    ]
