# Generated by Django 4.1.13 on 2025-11-30 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payroll", "0007_generatepayroll_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatepayroll",
            name="advance_adjustment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="generatepayroll",
            name="bonuses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="generatepayroll",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_payrolls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
