# Generated by Django 4.1.13 on 2025-12-02 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_degination_user_designation"),
        ("payroll", "0009_payrollhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeepayrolldetails",
            name="employeeprofile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_details",
                to="accounts.employeeprofile",
            ),
        ),
    ]
