# Generated by Django 4.1.13 on 2025-12-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0010_employeepayrolldetails_employeeprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeepayrolldetails",
            name="employeeprofile",
        ),
    ]
