# Generated by Django 4.1.13 on 2025-12-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0011_remove_employeepayrolldetails_employeeprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatepayroll",
            name="overtime_compensation",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="generatepayroll",
            name="overtime_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
