# Generated by Django 4.1.13 on 2025-12-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0012_generatepayroll_overtime_compensation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatepayroll",
            name="absent_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="generatepayroll",
            name="present_days",
            field=models.IntegerField(default=0),
        ),
    ]
