# Generated by Django 4.1.13 on 2025-12-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0013_generatepayroll_absent_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeepayrolldetails",
            name="education_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="employeepayrolldetails",
            name="fooding_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="employeepayrolldetails",
            name="medical_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="employeepayrolldetails",
            name="transport_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="generatepayroll",
            name="education_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="generatepayroll",
            name="fooding_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="generatepayroll",
            name="medical_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="generatepayroll",
            name="transport_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
