# Generated by Django 4.1.13 on 2025-12-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("total_paid_leaves", models.IntegerField(default=0)),
                ("total_unpaid_leaves", models.IntegerField(default=0)),
                ("used_paid_leaves", models.IntegerField(default=0)),
                ("used_unpaid_leaves", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
