# Generated by Django 4.1.13 on 2026-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricSyncStatus',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('last_run_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
