# Generated by Django 4.1.13 on 2026-07-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_biometricsyncstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavequota',
            name='causual_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='left_causual_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='left_privilege_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='left_sick_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='privilege_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='sick_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
