# Generated by Django 4.1.13 on 2025-12-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_leavequota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="paid_leave",
        ),
        migrations.RemoveField(
            model_name="leave",
            name="unpaid_leave",
        ),
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="paid",
                max_length=20,
            ),
        ),
    ]
