# Generated by Django 4.1.13 on 2025-12-05 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "attendance",
            "0003_remove_leave_paid_leave_remove_leave_unpaid_leave_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="decision_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="decision_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
