# Generated by Django 4.1.13 on 2026-07-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leavequota_causual_leaves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavequota',
            name='causual_leaves',
        ),
        migrations.RemoveField(
            model_name='leavequota',
            name='left_causual_leaves',
        ),
        migrations.RemoveField(
            model_name='leavequota',
            name='left_privilege_leaves',
        ),
        migrations.RemoveField(
            model_name='leavequota',
            name='left_sick_leaves',
        ),
        migrations.RemoveField(
            model_name='leavequota',
            name='privilege_leaves',
        ),
        migrations.RemoveField(
            model_name='leavequota',
            name='sick_leaves',
        ),
    ]
