# Generated by Django 4.1.13 on 2026-07-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_leavequota_causual_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavequota',
            name='paid_leave_use_as_causual_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='paid_leave_use_as_privilege_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavequota',
            name='paid_leave_use_as_sick_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
