# Generated by Django 4.1.13 on 2025-12-14 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0004_leave_decision_by_leave_decision_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="biometriclog",
            name="hr_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="marked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="biometriclog",
            name="marked_by_hr",
            field=models.BooleanField(default=False),
        ),
    ]
