# Generated by Django 4.1.13 on 2026-07-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_leavequota_paid_leave_use_as_causual_leaves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('paid_casual', 'Paid Casual Leave'), ('paid_sick', 'Paid Sick Leave'), ('paid_privilege', 'Paid Privilege Leave'), ('paid', 'Paid Leave'), ('unpaid', 'Unpaid Leave')], default='paid_casual', max_length=20),
        ),
    ]
