# Generated by Django 4.1.13 on 2026-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('paid_casual', 'Paid Casual Leave'), ('sick', 'Sick Leave'), ('paid_privilege', 'Paid Privilege Leave'), ('paid', 'Paid Leave'), ('unpaid', 'Unpaid Leave')], default='paid_casual', max_length=20),
        ),
    ]
