# Generated by Django 4.1.13 on 2026-02-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_holiday"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Holiday",
        ),
    ]
