# Generated by Django 4.1.13 on 2026-05-05 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0007_delete_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriclog',
            name='holiday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='holiday_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='biometriclog',
            name='holiday_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
