# Generated by Django 4.1.13 on 2026-05-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerequest',
            old_name='check_in_time',
            new_name='punch_time',
        ),
        migrations.RemoveField(
            model_name='attendancerequest',
            name='check_out_time',
        ),
        migrations.AddIndex(
            model_name='attendancerequest',
            index=models.Index(fields=['user', 'request_date', 'status'], name='attendance__user_id_d3328e_idx'),
        ),
    ]
