# Generated by Django 4.1.13 on 2026-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='location_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
