# Generated by Django 4.1.13 on 2026-08-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendancerequest_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerequest',
            name='location_captured',
        ),
    ]
