# Generated by Django 4.1.13 on 2026-08-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_attendancerequest_location_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
